import os
from building import *

cwd = GetCurrentDir()
src = Glob('src/*.c')
CPPPATH = [cwd, os.path.join(cwd, 'inc')]

group = DefineGroup('uMCN_example_cb', src, depend=['UMCN_USING_EXAMPLE_CB'], CPPPATH=CPPPATH)

Return('group')

